#####################################################
#                                                   #
#   This is the DEVELOPMENT docker-compose file     #
#                                                   #
#####################################################
version: '3.7'

services:
    db:
        image: mysql:8
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file: 
        # Use process.env in node.js code, like this 'process.env.ENV'.
        - ./docker_config/dev/mysql.dev.env
        environment: 
            - DB_USERNAME=nacho
            - DB_PASSWORD=nacho
        ports:
        # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
        # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
        # Crea el volumen (my-db) en el host que almacena de forma persistente el contenido del directorio '/var/lib/mysql' ubicado en el contendor.
            - my-db:/var/lib/mysql
            - ./docker_config/db-init:/docker-entrypoint-initdb.d  
            - /etc/timezone:/etc/timezone:ro
            - "/etc/localtime:/etc/localtime:ro"
        
    nids:
        image: nids
        container_name: nids
        network_mode: host
        build: 
            context: .
            dockerfile: ./NIDS/Dockerfile
        env_file: 
        - ./docker_config/dev/app_db.dev.env
        environment: 
            - DB_USERNAME=nacho
            - DB_PASSWORD=nacho
        ports: 
            - 8080:8080
        depends_on:
            - db
        volumes:
        - ./NIDS/:/usr/src/
        - /etc/timezone:/etc/timezone:ro
        - "/etc/localtime:/etc/localtime:ro"
        command: npm run start:dev

    frontend:
        image: frontend
        container_name: frontend
        build: 
            context: .
            dockerfile: ./frontend/Dockerfile
        env_file: 
        - ./docker_config/dev/app_db.dev.env
        ports: 
            - 8000:8000
        volumes:
        - ./frontend/:/usr/src/
        - /etc/timezone:/etc/timezone:ro
        - "/etc/localtime:/etc/localtime:ro"
        command: npm run start:dev

    
# Names our volume
volumes:
    my-db:

networks:
    default:
        ipam:
            config:
                - subnet: 172.19.0.1/24